# Generated by Django 5.1.1 on 2025-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Gov_Official_Person',
            field=models.BooleanField(default=False),
        ),
    ]
