# Generated by Django 5.1.1 on 2025-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_id_proof_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_Gov_Official_Person',
            new_name='granted_access',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_ambulanceOrganizer_Person',
            new_name='is_Gov_Official_Admin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_ambulanceOrganizer_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
