# Generated by Django 5.1.1 on 2025-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_gov_official_person_customuser_granted_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
