# Generated by Django 5.1.1 on 2025-06-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_id_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='psswordManager',
            fields=[
                ('pmid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
