# Generated by Django 5.1.1 on 2025-06-27 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_psswordmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordManager',
            fields=[
                ('pmid', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='psswordManager',
        ),
    ]
