# Generated by Django 5.1.1 on 2025-06-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordmanager_delete_psswordmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordmanager',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordmanager',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
