# Generated by Django 5.2.9 on 2025-12-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_passwordmanager_user_passwordmanager_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passwordManager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='granted_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Gov_Official',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_Gov_Official_Admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_ambulanceOrganizer_Admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
